made changes so that code will run when hit create preset
W0000 00:00:1753797235.868787   23704 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
❌ No valid selected_preset or label_csv_path
Creating new preset...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\yipju\AppData\Local\Programs\Python\Python311\Lib\tkinter__init.py", line 1948, in call
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\yipju\OneDrive\Desktop\FYPJ\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\yipju\OneDrive\Desktop\FYPJ\gui\change_preset.py", line 127, in create_new_preset
    self.create_preset_frame = CreatePreset(
                               ^^^^^^^^^^^^^
TypeError: CreatePreset.init__() missing 1 required positional argument: 'update_presets_callback

this error will pop out when hitting create preset, should fix said issue